server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cgq8qxgihvft.ap-northeast-2.rds.amazonaws.com:3306/one_pick
    username: root
    password: 4015pskc

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

#jwt:
#  key:
#    access: 2a10q42lY7Y18xqrFt1qbODZIO4OMTeOxnrCe7tF3n9bazJinVE7VH5Pi
#    refresh: 2a10q42lY7Y18xqrFt1qbODZIO4OMTeOxnrCe7tF3n9bazJinVE7VH5Pi
#  max-age:
#    access: 1800 # 60 * 30
#    refresh: 604800 # 60 * 60 * 24 * 7